# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 10

# [[main]]
#   name = "Shortcodes"
#   pageRef = "docs/shortcodes"
#   weight = 15

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 16

[[main]]
  name = "Talks"
  pageRef = "talks"
  weight = 16

[[main]]
  name = "News"
  pageRef = "news"
  weight = 17

[[main]]
  name = "Repositories"
  pageRef = "repositories"
  weight = 18

# [[main]]
#   name = "Merch"
#   url = "http://tee.pub/lic/qwSlWVBL5zc"
#   weight = 100

[[main]]
  identifier = "email"
  pre = "email"
  url = "mailto:xfz.zhao@gmail.com"
  weight = 300

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/xufeng-zhao-961a82286/"
  weight = 340 

[[main]]
  identifier = "twitter"
  pre = "twitter"
  url = "https://twitter.com/XfzZhao"
  weight = 350

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/xf-zhao"
  weight = 351

[[main]]
  identifier = "graduation-cap"
  pre = "graduation-cap"
  url = "https://scholar.google.com/citations?user=sLwQ22MAAAAJ"
  weight = 352

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


 [[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 10

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 20

 [[footer]]
   name = "Series"
   pageRef = "series"
   weight = 30